### PR TITLE
Fix bug - cookie can now handle more than 1 value being set

### PR DESCRIPTION
**Pull request by bootandy**

### CODE REVIEW

**Comment by peterbe** [comment]
How does this look in terms of how you use it?

**Comment by peterbe** [comment]
Also, without this patch, is it not possible to set more than 1 cookie.

**Comment by peterbe** [comment]
I tried to try your code on tests in one of my projects and it fails because it strangely appears that your branch is out of date. Can you merge it against the latest master and upgrade your branch?

**Comment by bootandy** [comment]
ok - I'm a noob at github pulling.  To be honest I copied your code - realised it wasn't working for multiple values in a cookie and just fixed it locally & cut n pasted back into the browser. I'll download the repo and do it properly.

**Comment by peterbe** [comment]
@bootandy if you need help with git and pull requesting and stuff then let me know. I'm sure you're on to something interesting which we should try to fix.

**Pull request closed without merging**
