### PR TITLE
 cookie can now handle more than 1 value being set

### PR DESCRIPTION
**Pull request by bootandy**
This pull is including a commit you made 3 months ago. I don't know why it would do that. I didn't know this repo existed until a week ago let alone 3 months ago.

This commit is to fix this behaviour:
I have the below code in my app but it doesn't work without the patch as the test framework only remembers 1 cookie. This is seen in python 2.7 with Tornado 2.2.

(In a tornado handler):
handler.set_secure_cookie('user_details_id', 'i like bananas')
handler.set_secure_cookie('user', 'andy')

According to the source Cookie extends dict so I assume that makes 'update()' behave like adding a new entry to a hash and therefore multiple update() calls are fine.
http://hg.python.org/cpython/file/2.7/Lib/Cookie.py

Let me know if you think this is ok. & If it merges correctly this time

### CODE REVIEW

**Comment by peterbe** [comment]
Yay!! https://github.com/peterbe/tornado-utils/commit/0b9ad1327edde5cccf085506fbedf86c125f62fb

It's working when testing my site. I'm going to see if I can improve polish it a bit further.

**Comment by peterbe** [comment]
You know, upon closer inspection. Why does it do the `while True` loop? This works perfectly fine:

``` python
    def _update_cookies(self, headers):
        try:
            sc = headers['Set-Cookie']
            cookies = escape.native_str(sc)
            self.cookies.update(Cookie.SimpleCookie(cookies))
        except KeyError:
            return
```

I tried by running around a handler that not only sets two cookies but one of them, the value contains commas. Works like a charm. 

What am I missing?

**Comment by bootandy** [comment]
Firstly, I'm not a http expert. But I can see that the existing version isn't setting all the values after multiple calls to set_secure_cookie in my handler. If I run my tests with the patched code all cookie values are set. If I run the old version they are not and my tests fail.

The 'while True:' loop is to make multiple calls to "self.cookies.update" - one for each entry in the cookie CSV string. 

Try writing a test as follows:
Write a handler that sets 2 values in a cookie in the first request. Then try and read both those values back in a second request. This fails for me.

I'm using Tornado 2.2 - python 2.7.

**Comment by peterbe** [comment]
Here's the test I use:

``` python
# the test
    def test_cookies(self):
        url=self.reverse_url('cookies')
        r=self.client.get(url)
        assert 'No cookies' in r.body
        self.client.post(url, {'foo': 1})
        r=self.client.get(url)
        assert 'No cookies' not in r.body
        assert 'foo=1' in r.body

        self.client.post(url, {'bar': 'one,two,three'})
        r=self.client.get(url)
        assert 'No cookies' not in r.body
        assert 'foo=1' in r.body
        assert 'bar=one,two,three' in r.body
```

``` python
# the handler
@route('/cookies/$', name='cookies')
class CookiesHandler(BaseHandler):

    def get(self):
        out = []
        if self.get_cookie('foo'):
            out.append('foo=%s' % self.get_cookie('foo'))
        if self.get_cookie('bar'):
            out.append('bar=%s' % self.get_cookie('bar'))

        if not out:
            out.append('No cookies')

        self.write('\n'.join(out))

    def post(self):
        if self.get_argument('foo', None):
            self.set_cookie('foo', self.get_argument('foo'))
        if self.get_argument('bar', None):
            self.set_cookie('bar', self.get_argument('bar'))

        self.write("Written")
```

This now works thanks to your code. But it doesn't need the `while True` loop thing. So, why do you think it needs it. All that strange finding around the `,` seems strange.

**Comment by bootandy** [comment]
Because if you change your test so 2 cookies are set **in the same request** it would fail:

modified test & handler:

```
def test_cookies(self):
   url=self.reverse_url('cookies')
   r=self.client.get(url)
   assert 'No cookies' in r.body
   self.client.post(url, {'foo': 1})
   r=self.client.get(url)
   assert 'No cookies' not in r.body
   assert 'foo=1' in r.body
   assert 'foo_at_same_time=1' in r.body

   self.client.post(url, {'bar': 'one,two,three'})
   r=self.client.get(url)
   assert 'No cookies' not in r.body
   assert 'foo=1' in r.body
   assert 'bar=one,two,three' in r.body
```

``` python
@route('/cookies/$', name='cookies')
class CookiesHandler(BaseHandler):

   def get(self):
       out = []
       if self.get_cookie('foo'):
           out.append('foo=%s' % self.get_cookie('foo'))
       if self.get_cookie('foo_at_same_time'):
           out.append('foo=%s' % self.get_cookie('foo'))
           out.append('foo_at_same_time=%s' % self.get_cookie('foo_at_same_time'))
       if self.get_cookie('bar'):
           out.append('bar=%s' % self.get_cookie('bar'))

       if not out:
           out.append('No cookies')

       self.write('\n'.join(out))

   def post(self):
       if self.get_argument('foo', None):
           self.set_cookie('foo', self.get_argument('foo'))
           self.set_cookie('foo_at_same_time', self.get_argument('foo'))
       if self.get_argument('bar', None):
           self.set_cookie('bar', self.get_argument('bar'))

       self.write("Written")
```

**Comment by peterbe** [comment]
Excellent! I can reproduce that too now.

**Pull request closed without merging**
